# Generated by Django 2.0.5 on 2018-05-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='string',
            new_name='puzzle_blank',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_solved',
            field=models.CharField(default=0, max_length=81),
            preserve_default=False,
        ),
    ]
